---
# Publish the Nix flake outputs to Cachix
# shamelessy stolen from:
# https://sourcegraph.com/github.com/helix-editor/helix/-/blob/.github/workflows/cachix.yml
name: Cachix
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 1 1-7,14-21 * 5"

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v22

      - name: Authenticate with Cachix
        uses: cachix/cachix-action@v12
        with:
          name: hurricanehrndz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake inputs
        run: >
          nix flake update --accept-flake-config --no-use-registries

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Flake: update input"
          default_author: github_actions

      - name: Build and Publish nix flake
        run: >
          cachix watch-exec hurricanehrndz -- nix build \
            --accept-flake-config \
            --show-trace
