---
# Publish the Nix flake outputs to Cachix
# shamelessy stolen from:
# https://sourcegraph.com/github.com/helix-editor/helix/-/blob/.github/workflows/cachix.yml
name: Cachix
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 1-7,14-21 * 5"

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v22

      - name: Authenticate with Cachix
        uses: cachix/cachix-action@v12
        with:
          name: hurricanehrndz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Watch store and push new
        run: cachix watch-store hurricanehrndz &

      - name: Build and Publish nix flake
        run: >
          nix build --show-trace
